name: Test Install Sponge

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: xdpxi/install-sponge@v1
        with:
          version: "1.1.1"
      - run: sponge -v
